# Example - 1

In [80]:
import numpy as np

In [81]:
list10 = [2, 3, 8.9, 103.3, 54.8]
array1 = np.array(list10) # conveted to 1-D
print(array1)

[   2.     3.     8.9  103.3   54.8]


In [82]:
array2 = array1 + 3
print(array2)

[   5.     6.    11.9  106.3   57.8]


In [16]:
array3 = array1 * 2
print(array3)

[   4.     6.    17.8  206.6  109.6]


In [17]:
array4 = array1 - 1.03
print(array4)

[   0.97    1.97    7.87  102.27   53.77]


In [19]:
array5 = array1 ** 2
print(array5)

[  4.00000000e+00   9.00000000e+00   7.92100000e+01   1.06708900e+04
   3.00304000e+03]


In [20]:
#same example with list

In [25]:
list11 = [2, 3, 8.9, 103.3, 54.8]
result = []
for val in list11:
    result.append(val + 3)
print(result)

[5, 6, 11.9, 106.3, 57.8]


In [26]:
# same using list comprehensions

In [27]:
result1 = [ val + 3 for val in list11]
print(result1)

[5, 6, 11.9, 106.3, 57.8]


In [28]:
# time comparision

In [29]:
v = np.random.randint(0, 100, 1000)

%timeit v + 1


1.96 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#  Example - 2

In [30]:
import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))

print(A)
print(B)
print("Adding to arrays: ")
print(A + B)

print("\nMultiplying two arrays: ")
#The elements are solely component-wise multiplied.
print(A * (B + 1))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Adding to arrays: 
[[ 12.  13.  14.]
 [ 22.  23.  24.]
 [ 32.  33.  34.]]

Multiplying two arrays: 
[[ 22.  24.  26.]
 [ 42.  44.  46.]
 [ 62.  64.  66.]]


In [31]:
# Matrix multiplication
np.dot(A,B)

array([[ 36.,  36.,  36.],
       [ 66.,  66.,  66.],
       [ 96.,  96.,  96.]])

# Example - 3 

In [34]:
# scalar and 1-D arrays in dot() function
# scalar
print(np.dot(3, 4))

# 1 - D array
A = np.array([3])
B = np.array([4])
print(A.ndim)
print(B.ndim)
print(np.dot(A, B))

A1 = np.array([3, -2])
B1 = np.array([-4, 1])
print(np.dot(A1, B1))

12
1
1
12
-14


In [45]:
# 2 - D arrays in dot() function
A2 = np.array([ [1, 2, 3], 
               [3, 2, 1] ])
B2 = np.array([ [2, 3, 4, -2], 
               [1, -1, 2, 3],
               [1, 2, 3, 0] ])
print("The dimension of A2", A2.ndim)
print("The dimension of B2",B2.ndim)
print("The Rows and Columns of A2 are:",A2.shape)
print("The Rows and Columns of B2 are:",B2.shape)

# matrix multiplication condition checking
print(A2.shape[-1] == B2.shape[-2], A2.shape[1]) 

#dot product
K1 = np.dot(A2,B2)
print("The dot product of A2 and B2 is:\n", K1)
print("The dimension of K1:", K1.ndim)
print("The Rows and Columns of K1 are:",K1.shape)

The dimension of A2 2
The dimension of B2 2
The Rows and Columns of A2 are: (2, 3)
The Rows and Columns of B2 are: (3, 4)
True 3
The dot product of A2 and B2 is:
 [[ 7  7 17  4]
 [ 9  9 19  0]]
The dimension of K1 2
The Rows and Columns of K1 are: (2, 4)


# Example - 4

In [46]:
# dot production of 3-D case
import numpy as np

A3 = np.array( [[[3, 1, 2], [4, 2, 2], [2, 4, 1]],
               [[3, 2, 2], [4, 4, 3], [4, 1, 1]],
               [[2, 2, 1], [3, 1, 3], [3, 2, 3]]])

B3 = np.array( [[[2, 3, 1], [2, 2, 4], [3, 4, 4]],
               [[1, 4, 1], [4, 1, 2], [4, 1, 2]],
               [[1, 2, 3], [4, 1, 1], [3, 1, 4]]])

print("The dimension of A3", A3.ndim)
print("The dimension of B3",B3.ndim)
print("The Rows and Columns of A3 are:",A3.shape)
print("The Rows and Columns of B3 are:",B3.shape)

# dot product
K2 = np.dot(A3, B3)
print("The dot product of A3 and B3 is:\n", K2)
print("The dimension of K2:", K2.ndim)
print("The Rows and Columns of K2 are:",K2.shape)
print("\nThe Result is:")
print(K2)


The dimension of A3 3
The dimension of B3 3
The Rows and Columns of A3 are: (3, 3, 3)
The Rows and Columns of B3 are: (3, 3, 3)
The dot product of A3 and B3 is:
 [[[[14 19 15]
   [15 15  9]
   [13  9 18]]

  [[18 24 20]
   [20 20 12]
   [18 12 22]]

  [[15 18 22]
   [22 13 12]
   [21  9 14]]]


 [[[16 21 19]
   [19 16 11]
   [17 10 19]]

  [[25 32 32]
   [32 23 18]
   [29 15 28]]

  [[13 18 12]
   [12 18  8]
   [11 10 17]]]


 [[[11 14 14]
   [14 11  8]
   [13  7 12]]

  [[17 23 19]
   [19 16 11]
   [16 10 22]]

  [[19 25 23]
   [23 17 13]
   [20 11 23]]]]
The dimension of K2: 4
The Rows and Columns of K2 are: (3, 3, 3, 3)

The Result is:
[[[[14 19 15]
   [15 15  9]
   [13  9 18]]

  [[18 24 20]
   [20 20 12]
   [18 12 22]]

  [[15 18 22]
   [22 13 12]
   [21  9 14]]]


 [[[16 21 19]
   [19 16 11]
   [17 10 19]]

  [[25 32 32]
   [32 23 18]
   [29 15 28]]

  [[13 18 12]
   [12 18  8]
   [11 10 17]]]


 [[[11 14 14]
   [14 11  8]
   [13  7 12]]

  [[17 23 19]
   [19 16 11]
   [16 10 22]

In [47]:
import numpy as np
X = np.array(
    [[[3, 1, 2],
      [4, 2, 2]],

     [[-1, 0, 1],
      [1, -1, -2]],
     
     [[3, 2, 2],
      [4, 4, 3]],

     [[2, 2, 1],
      [3, 1, 3]]])

Y = np.array(
    [[[2, 3, 1, 2, 1],
      [2, 2, 2, 0, 0],
      [3, 4, 0, 1, -1]],

     [[1, 4, 3, 2, 2],
      [4, 1, 1, 4, -3],
      [4, 1, 0, 3, 0]]])


R = np.dot(X, Y)



print("X.shape: ", X.shape, "   X.ndim: ", X.ndim)
print("Y.shape: ", Y.shape, "   Y.ndim: ", Y.ndim)
print("R.shape: ",     R.shape, "R.ndim: ", R.ndim)


print("\nThe result array R:\n")
print(R)

X.shape:  (4, 2, 3)    X.ndim:  3
Y.shape:  (2, 3, 5)    Y.ndim:  3
R.shape:  (4, 2, 2, 5) R.ndim:  4

The result array R:

[[[[ 14  19   5   8   1]
   [ 15  15  10  16   3]]

  [[ 18  24   8  10   2]
   [ 20  20  14  22   2]]]


 [[[  1   1  -1  -1  -2]
   [  3  -3  -3   1  -2]]

  [[ -6  -7  -1   0   3]
   [-11   1   2  -8   5]]]


 [[[ 16  21   7   8   1]
   [ 19  16  11  20   0]]

  [[ 25  32  12  11   1]
   [ 32  23  16  33  -4]]]


 [[[ 11  14   6   5   1]
   [ 14  11   8  15  -2]]

  [[ 17  23   5   9   0]
   [ 19  16  10  19   3]]]]


In [48]:
i = 0
for j in range(X.shape[1]):
    for k in range(Y.shape[0]):
        for m in range(Y.shape[2]):
            fmt = "    sum(X[{}, {}, :] * Y[{}, :, {}] :  {}"
            arguments = (i, j, k, m, sum(X[i, j, :] * Y[k, :, m]))
            print(fmt.format(*arguments))

    sum(X[0, 0, :] * Y[0, :, 0] :  14
    sum(X[0, 0, :] * Y[0, :, 1] :  19
    sum(X[0, 0, :] * Y[0, :, 2] :  5
    sum(X[0, 0, :] * Y[0, :, 3] :  8
    sum(X[0, 0, :] * Y[0, :, 4] :  1
    sum(X[0, 0, :] * Y[1, :, 0] :  15
    sum(X[0, 0, :] * Y[1, :, 1] :  15
    sum(X[0, 0, :] * Y[1, :, 2] :  10
    sum(X[0, 0, :] * Y[1, :, 3] :  16
    sum(X[0, 0, :] * Y[1, :, 4] :  3
    sum(X[0, 1, :] * Y[0, :, 0] :  18
    sum(X[0, 1, :] * Y[0, :, 1] :  24
    sum(X[0, 1, :] * Y[0, :, 2] :  8
    sum(X[0, 1, :] * Y[0, :, 3] :  10
    sum(X[0, 1, :] * Y[0, :, 4] :  2
    sum(X[0, 1, :] * Y[1, :, 0] :  20
    sum(X[0, 1, :] * Y[1, :, 1] :  20
    sum(X[0, 1, :] * Y[1, :, 2] :  14
    sum(X[0, 1, :] * Y[1, :, 3] :  22
    sum(X[0, 1, :] * Y[1, :, 4] :  2


In [49]:
print(K2[0])

[[[14 19 15]
  [15 15  9]
  [13  9 18]]

 [[18 24 20]
  [20 20 12]
  [18 12 22]]

 [[15 18 22]
  [22 13 12]
  [21  9 14]]]


# Example - 5

In [83]:
import numpy as np

A4 = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B4 = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])

print("The dimension of A4", A4.ndim)
print("The dimension of B4",B4.ndim)
print("The Rows and Columns of A4 are:",A4.shape)
print("The Rows and Columns of B4 are:",B4.shape)
K3 = A4 * B4
print(K3)
print(A4)
print(B4)

The dimension of A4 2
The dimension of B4 2
The Rows and Columns of A4 are: (3, 3)
The Rows and Columns of B4 are: (3, 3)
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
[[1 2 3]
 [2 2 2]
 [3 3 3]]
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]


In [84]:
MA4 = np.mat(A4)
MB4 = np.mat(B4)

K4 = MA4 * MB4
print(K4)

K5 = np.dot(A4,B4)
print(K5)



[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Example  6

In [52]:
import numpy as np

A5 = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B5 = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])

A5 == B5


array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]], dtype=bool)

In [53]:
# complete array comparision
print(np.array_equal(A5, B5))
print(np.array_equal(A5, A5))

False
True


# Example  7

In [54]:
a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])

print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


# Example - 8

In [86]:
import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
print(A.shape)
print(B.shape)
print(A.ndim)
print(B.ndim)

print("Multiplication with broadcasting: ")
print(A * B)
print("... and now addition with broadcasting: ")
print(A + B)


(3, 3)
(3,)
2
1
Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [56]:
B = np.array([[1, 2, 3],] * 3)
print(B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [88]:
# second example:
B = np.array([1, 2, 3])
B[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [58]:
A * B[:, np.newaxis]

array([[11, 12, 13],
       [42, 44, 46],
       [93, 96, 99]])

In [59]:
np.array([[1, 2, 3],] * 3).transpose()


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [60]:
# third example

A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [61]:
A[:, np.newaxis] * B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [62]:
# another way is : without broadcasting
import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])

B = np.array([1, 2, 3])

B = B[np.newaxis, :]
B = np.concatenate((B, B, B))

print("Multiplication: ")
print(A * B)
print("... and now addition again: ")
print(A + B)


Multiplication: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition again: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [63]:
import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])

B = np.tile(np.array([1, 2, 3]), (3, 1))

print(B)

print("Multiplication: ")
print(A * B)
print("... and now addition again: ")
print(A + B)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Multiplication: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition again: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [64]:
# 3-D broadcasting


A = np.array([ [[3, 4, 7], [5, 0, -1] , [2, 1, 5]],
      [[1, 0, -1], [8, 2, 4], [5, 2, 1]],
      [[2, 1, 3], [1, 9, 4], [5, -2, 4]]])

B = np.array([ [[3, 4, 7], [1, 0, -1], [1, 2, 3]] ])

B * A


array([[[ 9, 16, 49],
        [ 5,  0,  1],
        [ 2,  2, 15]],

       [[ 3,  0, -7],
        [ 8,  0, -4],
        [ 5,  4,  3]],

       [[ 6,  4, 21],
        [ 1,  0, -4],
        [ 5, -4, 12]]])

In [65]:


B = np.array([1, 2, 3])

B = B[np.newaxis, :]
print(B.shape)
B = np.concatenate((B, B, B)).transpose()
print(B.shape)
B = B[:, np.newaxis]
print(B.shape)
print(B)

print(A * B)



(1, 3)
(3, 3)
(3, 1, 3)
[[[1 1 1]]

 [[2 2 2]]

 [[3 3 3]]]
[[[ 3  4  7]
  [ 5  0 -1]
  [ 2  1  5]]

 [[ 2  0 -2]
  [16  4  8]
  [10  4  2]]

 [[ 6  3  9]
  [ 3 27 12]
  [15 -6 12]]]


# Example - 9

In [69]:
import numpy as np

A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])
print("A:")
print(A)
print("The dimension of A:", A.ndim)
print("The rows and columns of A are ", A.shape)

Flattened_X = A.flatten()
print(Flattened_X)

print("Different orders in flatten:")

print(A.flatten(order="C"))
print(A.flatten(order="F"))
print(A.flatten(order="A"))

A:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
The dimension of A: 3
The rows and columns of A are  (3, 4, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Different orders in flatten:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Example - 10

In [70]:
print(A.ravel())

print(A.ravel(order="A"))

print(A.ravel(order="F"))

print(A.ravel(order="A"))

print(A.ravel(order="K"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#  Example - 11

In [90]:
X = np.array(range(24))
print(X)
Y = X.reshape((3,8))
Y

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

# Example - 12

In [72]:
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])
c = np.concatenate((x,y,z))
print(c)

[11 22 18  7  6  1  3  5]


In [73]:
#multidimensional arrays concatenations


x = np.array(range(24))
x = x.reshape((3,4,2))
y = np.array(range(100,124))
y = y.reshape((3,4,2))
z = np.concatenate((x,y))
print(z)



[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]]

 [[100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[116 117]
  [118 119]
  [120 121]
  [122 123]]]


In [74]:
z = np.concatenate((x,y),axis = 1)
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]
  [100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]
  [108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]
  [116 117]
  [118 119]
  [120 121]
  [122 123]]]


# Example - 13

In [91]:
x = np.array([2,5,18,14,4])
print(x.ndim)
y = x[:, np.newaxis]
print(y)
print(y.ndim)

1
[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]
2


In [92]:
#Vector Stacking

A = np.array([3, 4, 5])
B = np.array([1,9,0])

print(np.row_stack((A, B)))

print(np.column_stack((A, B)))

np.shape(A)

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [77]:
A = np.array([[3, 4, 5],
              [1, 9, 0],
              [4, 6, 8]])
np.column_stack((A, A, A))

array([[3, 4, 5, 3, 4, 5, 3, 4, 5],
       [1, 9, 0, 1, 9, 0, 1, 9, 0],
       [4, 6, 8, 4, 6, 8, 4, 6, 8]])

In [78]:
np.column_stack((A[0], A[0], A[0]))

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [79]:
np.dstack((A, A, A))

array([[[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[1, 1, 1],
        [9, 9, 9],
        [0, 0, 0]],

       [[4, 4, 4],
        [6, 6, 6],
        [8, 8, 8]]])

# Example - 14

In [93]:
import numpy as np
x = np.array([ [1, 2], [3, 4]])
np.tile(x, (3,4)) # reps 3 --> row, 4 --> colun

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [98]:

import numpy as np

x = np.array([ 3.4])

y = np.tile(x, (5,)) 

print(y)

[ 3.4  3.4  3.4  3.4  3.4]


In [95]:

import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.tile(x, 2))


[[1 2 1 2]
 [3 4 3 4]]


In [96]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.tile(x, (2, 1)))



[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [97]:

import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.tile(x, (2, 2)))



[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
