In [1]:
#import numpy as np

# Example - 1

In [3]:
import numpy as np
data1 = np.ones((5,8))
print(data1)

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]


In [3]:
data2 = np.ones((3,4),dtype=int)
print(data2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Example - 2

In [7]:
import numpy as np
data3 = np.zeros((2,4), dtype = int)
print(data3)

[[0 0 0 0]
 [0 0 0 0]]


# Example - 3

In [13]:
import numpy as np
a = np.array([2,5,18,14,4])
print(a)
print(a.shape)
data4 = np.ones_like(a)
print(data4)

[ 2  5 18 14  4]
(5,)
[1 1 1 1 1]


In [14]:
data5 = np.zeros_like(a)
print(data5)

[0 0 0 0 0]


# Example - 4

In [15]:
import numpy as np
np.empty((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

# Example - 5

In [17]:
#numpy.copy()
import numpy as np

data6 = np.array([[42,22,12],[44,53,66]], order='F')
data7 = data6.copy()
print(data6)
print(data7)

[[42 22 12]
 [44 53 66]]
[[42 22 12]
 [44 53 66]]


In [18]:
data6[0,0] = 1001
print(data6)

print(data7)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]


In [19]:
print(data6.flags['C_CONTIGUOUS'])
print(data7.flags['C_CONTIGUOUS'])

False
True


# Example - 6

In [12]:
import numpy as np

data8 = np.array([[42,22,12],[44,53,66]], order='F')
data9 = data8.copy()
data8[0,0] = 1001
print(data8)

print(data9)

print(data8.flags['C_CONTIGUOUS'])
print(data9.flags['C_CONTIGUOUS'])

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]
False
True


# Example - 7

In [20]:
import numpy as np
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
np.identity(5, int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Example -8

In [24]:
import numpy as np

np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [19]:
np.eye(5, 8, k=0, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [23]:
np.eye(5, 8, k=-1, dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0]])

# Example - 9

In [27]:
import numpy as np

data_type = np.dtype(np.int16)
print(data_type)

list10 = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

data10 = np.array(list10, dtype=data_type)

print(data10)

int16
[[ 3  8  9]
 [ 1 -7  0]
 [ 4 12  4]]


# Example - 10

In [29]:
import numpy as np

data_type1 = np.dtype([('density', np.int32)])

list11 = np.array([(393,), (337,), (256,)], dtype=data_type1)

print(list11)

print("\nThe internal representation:")
print(repr(list11))

[(393,) (337,) (256,)]

The internal representation:
array([(393,), (337,), (256,)],
      dtype=[('density', '<i4')])


In [23]:
print(list11['density'])

[393 337 256]


In [31]:
dt = np.dtype([('density', 'i4')])
list12 = np.array([(393,), (337,), (256,)],
             dtype=dt)
print(list12)

print(repr(list12))

[(393,) (337,) (256,)]
array([(393,), (337,), (256,)],
      dtype=[('density', '<i4')])


In [33]:
dt101 = np.dtype([('sepal.length', '<d'), ('sepal.width', '<d'), ('petal.length', '<d'), ('petal.width', '<d'), ('variety', 'S10')])

In [34]:
iris_table = np.array([
    (5.1,3.5,1.4,0.2,'Setosa'),
    (6.2,2.2,4.5,1.5,'Versicolor'),
    (6.9,3.1,5.4,2.1,'Virginica')],
    dtype=dt101)

In [35]:
print(iris_table[:5])

[( 5.1,  3.5,  1.4,  0.2, b'Setosa')
 ( 6.2,  2.2,  4.5,  1.5, b'Versicolor')
 ( 6.9,  3.1,  5.4,  2.1, b'Virginica')]


In [37]:
print(iris_table['sepal.length'])
print(iris_table['sepal.width'])
print(iris_table['variety'])
print(iris_table['petal.width'])
print(iris_table['petal.length'])

[ 5.1  6.2  6.9]
[ 3.5  2.2  3.1]
[b'Setosa' b'Versicolor' b'Virginica']
[ 0.2  1.5  2.1]
[ 1.4  4.5  5.4]


In [38]:
data_type12 = np.dtype([('sepal.length', '<d'), ('sepal.width', '<d'), ('petal.length', '<d'), ('petal.width', '<d'), ('variety', np.unicode,10)])

In [39]:
iris_table2 = np.array([
    (5.1,3.5,1.4,.2,'Setosa'),
    (6.2,2.2,4.5,1.5,'Versicolor'),
    (6.9,3.1,5.4,2.1,'Virginica')],
    dtype=data_type12)

In [40]:
print(iris_table2[:5])

[( 5.1,  3.5,  1.4,  0.2, 'Setosa') ( 6.2,  2.2,  4.5,  1.5, 'Versicolor')
 ( 6.9,  3.1,  5.4,  2.1, 'Virginica')]


# Example - 11

In [41]:
np.savetxt("iris_table201.csv", iris_table2, fmt="%f,%f,%f,%f,%s", delimiter=",")

# Example - 12

In [44]:
iris_table3 = np.loadtxt("iris_table2.csv", dtype=data_type12, converters={0: lambda x: x.decode('utf-8')}, delimiter=",")

In [45]:
print(iris_table3)

[( 5.1,  3.5,  1.4,  0.2, 'Setosa') ( 6.2,  2.2,  4.5,  1.5, 'Versicolor')
 ( 6.9,  3.1,  5.4,  2.1, 'Virginica')]
