# Example - 1

In [57]:
# normal python
import random as ran
random_number = ran.random()
print(random_number)

0.2808854774355338


In [52]:
from random import SystemRandom
crypto = SystemRandom()
print(crypto.random())

0.9955538523192247


In [3]:
# Generate a list of Random Numbers
# create a list of random numbers by repeatedly calling random()

In [56]:
import random

def random_list(n, secure=True):
    random_floats = []
    if secure:
        crypto = random.SystemRandom()
        random_float = crypto.random
    else:
        random_float = random.random
    for _ in range(n):
        random_floats.append(random_float())
    return random_floats

print(random_list(10, secure=False))

[0.3495223929742234, 0.13949936187375755, 0.6113558770680998, 0.7769120429817453, 0.9510357858775678, 0.7229576845880394, 0.11070371713857952, 0.7406603807972387, 0.7222208041377557, 0.04354953361872127]


In [5]:
# fast and most effective to generate random data 

In [53]:
import numpy as np 
np.random.random(10)

array([ 0.02401076,  0.45127345,  0.58869302,  0.09514847,  0.79096481,
        0.34144144,  0.76676186,  0.96769326,  0.77528171,  0.92675754])

#  Example - 2

In [63]:
import numpy as np
#import random 
list_of_random_floats = np.random.random(100)
#print(list_of_random_floats)
print("Total sum of the random values is before Normalization:")
sum_of_values = list_of_random_floats.sum()
print(sum_of_values)
normalized_values = list_of_random_floats / sum_of_values
print(normalized_values)
print("Total sum of the normalized values is:")
print(normalized_values.sum())

Total sum of the random values is before Normalization:
50.2319103461
[ 0.00505528  0.00455459  0.00433508  0.01349439  0.00701705  0.01367641
  0.00591724  0.01620918  0.00354694  0.01221728  0.01149196  0.00578469
  0.01675198  0.01101294  0.01125078  0.0041009   0.00820796  0.01568505
  0.0147227   0.0064045   0.00782504  0.00549529  0.00742812  0.01696527
  0.0025249   0.01215854  0.00964244  0.01389564  0.00273053  0.01492766
  0.00621334  0.01978114  0.01984056  0.00259657  0.01502935  0.0101216
  0.00509855  0.01988456  0.00338847  0.0082034   0.01682459  0.00313932
  0.01937414  0.01600573  0.01496238  0.01107837  0.00379727  0.0101935
  0.00935125  0.00770225  0.01963567  0.01424372  0.00586987  0.01501494
  0.01817589  0.00553936  0.01771898  0.00617359  0.0050673   0.00920121
  0.01657042  0.0083511   0.00133284  0.00556033  0.0135125   0.0024834
  0.00200747  0.00282246  0.00727859  0.01502034  0.00099276  0.01968394
  0.00650771  0.00179859  0.00797585  0.00582148  0.01127

# Example - 3

In [2]:
from random import SystemRandom
sr = SystemRandom() # create an instance of the SystemRandom class
    

def generate_password(length, valid_chars=None):
    if valid_chars==None:
        valid_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        valid_chars += valid_chars.lower() + "0123456789"
    
    password = ""
    counter = 0
    while counter < length:
        rnum = sr.randint(0, 128)
        char = chr(rnum)
        if char in valid_chars:
            password += chr(rnum)
            counter += 1
            #print(password)
    return password

print("Automatically generated password by Python: " + generate_password(8))

Automatically generated password by Python: BL9VescS


# Example - 4

In [7]:
import numpy as np

print(np.random.randint(1, 7))
print(np.random.randint(1, 7, size=1))
print(np.random.randint(1, 7, size=10))
print(np.random.randint(1, 7, size=(10,))) # the same as the previous one
print(np.random.randint(1, 7, size=(5, 4)))

[[4 5 6 3]
 [5 4 6 3]
 [6 2 6 2]
 [1 2 2 3]
 [3 1 1 4]]


In [8]:
# normal python to generate random number
# Scenario virtual dice: # the rolling of the die" an experiment with a result from the set of possible outcomes {1, 2, 3, 4, 5, 6}
import random

outcome = random.randint(1,6)  
print(outcome)

6


In [9]:
# Roll the virtual dice 10 times
import random

[ random.randint(1, 6) for _ in range(10) ]

# this task can be done very easily using numpy


[4, 6, 5, 5, 3, 6, 3, 3, 1, 1]

In [10]:
# numpy package to roll dice 10 times
import numpy as np

outcome = np.random.randint(1, 7, size=10)
print(outcome)

[6 1 6 3 6 4 5 3 1 5]


# Example - 5

In [11]:
# normal python
from random import choice

possible_destinations = ["Berlin", "Hamburg", "Munich","Amsterdam", "London", "Paris", 
                         "Zurich", "Heidelberg", "Strasbourg", "Augsburg", "Milan", "Rome"]

print(choice(possible_destinations))

Heidelberg


In [12]:
# using numpy package, which is convient to select random choices.
from numpy.random import choice

print(choice(possible_destinations))

Zurich


In [13]:
# with number of chioces

x1 = choice(possible_destinations, size=3)
print(x1)
x2 = choice(possible_destinations, size=(3, 4))
print(x2)

['London' 'Munich' 'Paris']
[['Zurich' 'Hamburg' 'Rome' 'Milan']
 ['Augsburg' 'Augsburg' 'Hamburg' 'Hamburg']
 ['Heidelberg' 'London' 'Milan' 'Augsburg']]


In [14]:
#You might have noticed that the city names can have multiple occurrences.
#We can prevent this by setting the optional parameter "replace" to "False":

print(choice(possible_destinations, size=(3, 4), replace=False))

[['Zurich' 'Milan' 'Berlin' 'Munich']
 ['Amsterdam' 'Strasbourg' 'Paris' 'London']
 ['Rome' 'Augsburg' 'Heidelberg' 'Hamburg']]


# Example - 6

In [15]:
import numpy as np

x = np.random.random_sample((3, 4))
print(x)

[[ 0.85738873  0.75688816  0.85231962  0.15099952]
 [ 0.87157119  0.71824181  0.8224037   0.70592065]
 [ 0.8186682   0.79955086  0.74371912  0.47030649]]


In [20]:
# random_sample with an integer --> gets 1-D

x = np.random.random_sample(7)
print(x)

y = np.random.random_sample((7,))
print(y)

[ 0.37902523  0.82791236  0.2178715   0.59786735  0.05736826  0.43370229
  0.53854409]
[ 0.05939819  0.84776194  0.23146121  0.78637022  0.51396878  0.0928221
  0.49240992]


In [21]:
#  generate arrays with values from an arbitrary interval [a, b)

a = -3.4
b = 5.9

A = (b - a) * np.random.random_sample((3, 4)) + a
print(A)


[[ 1.48421367  3.35148413  0.85477827  2.13213765]
 [ 3.4822453   2.746508    2.0872161   1.46740112]
 [-0.83526424 -1.77732046  0.5972274   0.57578647]]


In [16]:
# normal python to create samples from population
import random

print(random.sample(range(1, 50), 6))

[3, 15, 33, 24, 6, 10]


# Example - 7

In [18]:
x = np.array([3,2])
y = np.array([5,1])
z = x + y   #check the output
print(z)
x = np.array([1,2,3])
y = np.array([-7,8,9])
print(np.dot(x,y))  #check the output
dot = np.dot(x,y)
print(dot)
x_modulus = np.sqrt((x*x).sum())
print(x_modulus)
y_modulus = np.sqrt((y*y).sum())
print(y_modulus)
cos_angle = dot / x_modulus / y_modulus  # cosine of angle between x and y
print(cos_angle)
angle = np.arccos(cos_angle)
print(angle)
print(angle * 360 / 2 / np.pi) # angle in degrees

[8 3]
36
36
3.74165738677
13.9283882772
0.690776600808
0.808233789011
46.3083849702


# Example - 8

In [19]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)) )
x * y

array([[ 2,  6],
       [15, -5]])

In [20]:
x = np.matrix( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
x * y

matrix([[17,  1],
        [28,  1]])

# Example - 9

In [21]:
x = np.array( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
np.dot(x,y)

matrix([[17,  1],
        [28,  1]])

In [22]:
# another way
np.mat(x) * np.mat(y)

matrix([[17,  1],
        [28,  1]])

# Example - 10

In [23]:
x = np.array([0,0,1])
y = np.array([0,1,0])
np.cross(x,y)

array([-1,  0,  0])

In [24]:
np.cross(y,x)

array([1, 0, 0])

# Example - 11

In [25]:
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)

np.savetxt("test.txt", x)

In [27]:
# other formats 
np.savetxt("test2.txt", x, fmt="%2.3f", delimiter=",")
np.savetxt("test3.txt", x, fmt="%04d", delimiter=" :-) ")

# Example - 12

In [30]:
y = np.loadtxt("test.txt")
print(y)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [31]:
y = np.loadtxt("test2.txt", delimiter=",")
print(y)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [32]:
y = np.loadtxt("test3.txt", delimiter=" :-) ")
print(y)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [34]:
# It's also possible to choose the columns by index:

y = np.loadtxt("test3.txt", delimiter=" :-) ", usecols=(0,2))
print(y)

[[ 1.  3.]
 [ 4.  6.]
 [ 7.  9.]]


# Example  -13

In [35]:
dt = np.dtype([('time', [('min', int), ('sec', int)]),
               ('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10
x['temp'] = 98.25
print(x)

fh = open("test6.txt", "bw")
x.tofile(fh)

[((10, 0),  98.25)]


# Example - 14

In [36]:
fh = open("test6.txt", "rb")

np.fromfile(fh, dtype=dt)

array([((10, 0),  98.25)],
      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])

In [39]:
4 * 41

164

In [40]:
import numpy as np
import os

# platform dependent: difference between Linux and Windows
#data = np.arange(50, dtype=np.int)

data = np.arange(50, dtype=np.int32)
data.tofile("test7.txt")

fh = open("test7.txt", "rb")
# 4 * 32 = 128
fh.seek(128, os.SEEK_SET)

x = np.fromfile(fh, dtype=np.int32)
print(x)

[41 42 43 44 45 46 47 48 49]


# Example - 15

In [41]:
import numpy as np

print(x)

from tempfile import TemporaryFile

outfile = TemporaryFile()

x = np.arange(10)
np.save(outfile, x)

outfile.seek(0) # Only needed here to simulate closing & reopening file
np.load(outfile)

[41 42 43 44 45 46 47 48 49]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])